apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
      release: "1"

  template:
    metadata:
      labels:
        app: webapp
        release: "1"
        
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release2
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
    release: "1"

  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080

  type: NodePort