apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-tracker

spec:
  replicas: 1
  selector:
    matchLabels:
      app: position-tracker
      release: "1"

  template:
    metadata:
      labels:
        app: position-tracker
        release: "1"
        
    spec:
      containers:
        - name: position-tracker
          image: richardchesterwood/k8s-fleetman-position-tracker:release3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker
    release: "1"

  ports:
    - name: http
      port: 8080
      
  type: ClusterIP
