apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue

spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
      release: "1"

  template:
    metadata:
      labels:
        app: queue
        release: "1"
        
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-queue:release2


---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
    release: "1"

  ports:
    - name: admin-console
      port: 8161
      targetPort: 8161
      nodePort: 30010
    - name: endpoint
      port: 61616
      
  type: NodePort
