apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # This defines which pods are going to be represented by this service
  # Service becomes network endpoint for other services or external users
  selector:
    app: webapp
    release: "0-5"

  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080

  type: NodePort